### ISSUE TITLE
TokenExpiredError after too long

### ISSUE THREAD

**Issue by cadesalaberry** [NOMAD-Live/nomad-live-dashboard#9]
```
127.0.0.1 - - [05/May/2015 14:39:18] "POST /api/search HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/ricocheteur/.local/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/ricocheteur/.local/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/ricocheteur/.local/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ricocheteur/.local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ricocheteur/.local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ricocheteur/.local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ricocheteur/.local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ricocheteur/.local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ricocheteur/Apps/nomad-live-dashboard/server.py", line 90, in api
    response = kickflip_session.post(endpoint, request.data)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 504, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/ricocheteur/.local/lib/python2.7/site-packages/requests_oauthlib/oauth2_session.py", line 277, in request
    http_method=method, body=data, headers=headers)
  File "/home/ricocheteur/.local/lib/python2.7/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 194, in add_token
    raise TokenExpiredError()
TokenExpiredError: (token_expired)
127.0.0.1 - - [05/May/2015 14:39:28] "POST /api/search HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/ricocheteur/.local/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/ricocheteur/.local/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/ricocheteur/.local/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ricocheteur/.local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ricocheteur/.local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ricocheteur/.local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ricocheteur/.local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ricocheteur/.local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ricocheteur/Apps/nomad-live-dashboard/server.py", line 90, in api
    response = kickflip_session.post(endpoint, request.data)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 504, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/ricocheteur/.local/lib/python2.7/site-packages/requests_oauthlib/oauth2_session.py", line 277, in request
    http_method=method, body=data, headers=headers)
  File "/home/ricocheteur/.local/lib/python2.7/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 194, in add_token
    raise TokenExpiredError()
TokenExpiredError: (token_expired)
127.0.0.1 - - [05/May/2015 14:39:38] "POST /api/search HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/ricocheteur/.local/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/ricocheteur/.local/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/ricocheteur/.local/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ricocheteur/.local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ricocheteur/.local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ricocheteur/.local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ricocheteur/.local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ricocheteur/.local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ricocheteur/Apps/nomad-live-dashboard/server.py", line 90, in api
    response = kickflip_session.post(endpoint, request.data)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 504, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/ricocheteur/.local/lib/python2.7/site-packages/requests_oauthlib/oauth2_session.py", line 277, in request
    http_method=method, body=data, headers=headers)
  File "/home/ricocheteur/.local/lib/python2.7/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 194, in add_token
    raise TokenExpiredError()
TokenExpiredError: (token_expired)
127.0.0.1 - - [05/May/2015 14:39:48] "POST /api/search HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/ricocheteur/.local/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/ricocheteur/.local/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/ricocheteur/.local/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ricocheteur/.local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ricocheteur/.local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ricocheteur/.local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ricocheteur/.local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ricocheteur/.local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ricocheteur/Apps/nomad-live-dashboard/server.py", line 90, in api
    response = kickflip_session.post(endpoint, request.data)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 504, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/ricocheteur/.local/lib/python2.7/site-packages/requests_oauthlib/oauth2_session.py", line 277, in request
    http_method=method, body=data, headers=headers)
  File "/home/ricocheteur/.local/lib/python2.7/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 194, in add_token
    raise TokenExpiredError()
TokenExpiredError: (token_expired)
```

**Comment by cadesalaberry** [comment]
Was related to kickflip only.
